### PR TITLE
Update the GORM version to the last upstream (2016, Sep 25)

### PR DESCRIPTION
**Pull request by deni64k**

### CODE REVIEW

**Comment by slockij** [comment]
I'll not review every single piece :) 2 questions:
1. does our "no WHERE clause" still works?
2. Do we have UTC normalization still in place?
I don't remember any other adjustments we did.

**Comment by deni64k** [comment]
I cherry-picked all our commits that are not in the upstream. So, both answers yes.
http://take.ms/OYY5X

**Review by slockij — APPROVED** [review]
good to go!

**Comment by deni64k** [comment]
Pushed as `master`

**Pull request closed without merging**
